version: "3"

services:
    db:
        image: postgres:15
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - ${DB_PORT}:5432
        volumes:
            - ./docker-data/db:/var/lib/postgresql/data

    redis:
        image: redis:7
        restart: unless-stopped
        ports:
            - ${REDIS_PORT}:6379
        volumes:
            - ./docker-data/redis:/data

    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./apps/backend/Dockerfile
        volumes:
            - /var/www/html/ezcook/api/images/:/apps/backend/images/
        ports:
            - "5000:5000"
        depends_on:
            - db

    frontend:
        build:
            context: .
            dockerfile: ./apps/frontend/Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - backend
