version: "3"

services:
db:
    image: postgres:15
    restart: always
    env_file:
        - ./apps/backend/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data


    redis:
        image: redis:7
        restart: always
        env_file:
            - ./apps/backend/.env
        ports:
        - ${REDIS_PORT}:6379
        volumes:
        - ./docker-data/redis:/data


    backend:
        restart: always
        build:
            context: ./apps/backend/
            dockerfile: ./apps/backend/Dockerfile
        env_file:
            - ./apps/backend/.env

        volumes:
            - /code
            - ./images:/app/backend/images/
        ports:
            - "5000:5000"
        depends_on:
            - db

    frontend:
        build: ./apps/frontend
        env_file:
            - ./apps/frontend/.env

        ports:
            - 3000:3000
        depends_on:
            - backend

    nginx:
        build: ./nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./images:/usr/share/nginx/food_pics:ro
        depends_on:
            - frontend
